- name: HTML
  production:
    exclude:
    - /bin/.*
    - /conf/.*
    - /docs/.*
    - /lib/.*
    - /tutorials/classes/.*
    - /tutorials/docs/.*
    - /tutorials/images/.*
  test:
    include:
      - /src/.*
