exclude:
  - /bin/.*
  - /conf/.*
  - /docs/.*
  - /lib/.*
  - /tutorials/classes/.*
  - /tutorials/docs/.*
  - /tutorials/images/.*
include:
  - /src/.*
  - /examples/mbeans/dynamic/src/.*
  - /examples/mbeans/model/src/.*
  - /examples/mbeans/standard/src/.*
  - /examples/notification/src/.*
  - /tutorials/src/.*
